feat:
  - head-branch: ["^feature/", "feature/"]

fix:
  - head-branch: ["^fix/", "fix/"]

chore:
  - head-branch: ["^chore/", "chore/"]

ci:
  - head-branch: ["^ci/", "ci/"]
  - changed-files:
    - any-glob-to-any-file: [".github/**"]

backend:
  - changed-files:
    - any-glob-to-any-file: ["Foldy/src/**/*.java"]

frontend:
  - changed-files:
    - any-glob-to-any-file: ["Foldy/src/main/resources/templates/**"]

docker:
  - changed-files:
    - any-glob-to-any-file: ["Foldy/Dockerfile"]

version:
  - head-branch: ["^version/", "version/"]