# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: Foldy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/foldy?serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:foldy}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
jwt:
  secret: foldy-secret-key-foldy-secret-key-foldy
  expiration: 86400000
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
      
server:
  port: 8080

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:team3-foldy-storage}
    presigned-url-expiration-minutes: 10